name: Startup Spaza
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50193
title: Startup Spaza
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-78632252-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
